micronaut.application.name=core-account
micronaut.netty.event-loops.default.num-threads=4

micronaut.security.enabled=true
micronaut.security.authentication=bearer
micronaut.security.token.jwt.enabled=true
micronaut.security.token.roles-name='realm_access'
micronaut.security.oauth2.clients.default.grant-type=client_credentials
micronaut.security.oauth2.clients.default.client-secret=${FINANCE_ACCOUNT_CLIENT_SECRET:`w5p9js1pXs9gPcwA9BtzKwS4p4ps8M9d`}
micronaut.security.oauth2.clients.default.client-id=${FINANCE_ACCOUNT_CLIENT_ID:`finance_client_id`}
micronaut.security.oauth2.clients.defaul.openid.issuer=${FINANCE_ACCOUNT_OIDC_ISSUER_DOMAIN:`http://192.168.20.5:7777`}/realms/${FINANCE_ACCOUNT_KEYCLOAK_REALM:`finance-account`}

r2dbc.datasources.default.url=r2dbc:postgresql://${FINANCE_ACCOUNT_DB_HOST:`localhost`}:${FINANCE_ACCOUNT_DB_PORT:`5432`}/${FINANCE_ACCOUNT_DB_NAME:`finance-account`}
r2dbc.datasources.default.username=${FINANCE_ACCOUNT_DB_USERNAME:`postgres`}
r2dbc.datasources.default.password=${FINANCE_ACCOUNT_DB_PASSWORD:`postgres`}
r2dbc.datasources.default.dialect=postgres
r2dbc.datasources.default.schema-generate=create_drop

nats.default.addresses=${NATS_HOSTS:`nats://192.168.20.5:4222`}