services:
  core-account:
    build:
      context: ../core/account
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#      - ../core/account/build/libs:/app/build #В этом нет смысла при деплое на виртуалку
    ports:
      - "8100:8080"
    env_file:
      - ../.env
    restart: always

  core-audit:
    build:
      context: ../core/audit
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - /gradle.properties:/app/gradle.properties
      - /core/audit/build:/app/build

  core-gateway:
    build:
      context: ../core/gateway
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - /gradle.properties:/app/gradle.properties
      - /core/gateway/build:/app/build

  core-transaction:
    build:
      context: ../core/transaction
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - /gradle.properties:/app/gradle.properties
      - /core/transaction/build:/app/build

  core-user:
    build:
      context: ../core/user
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - /gradle.properties:/app/gradle.properties
      - /core/user/build:/app/build
