services:
  infra-keycloak:
    container_name: keycloak
    build:
      context: ../infra/keycloak
      dockerfile: Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7777:7777"
    env_file:
      - ../.env
    restart: always

  infra-nats:
    build:
      context: ../infra/nats
      dockerfile: Dockerfile

  infra-kafka:
    build:
      context: ../infra/kafka
      dockerfile: Dockerfile

  infra-kcsql:
    build:
      context: ../infra/kcsql
      dockerfile: Dockerfile

  infra-nginx:
    build:
      context: ../infra/nginx
      dockerfile: Dockerfile

  infra-psql:
    build:
      context: ../infra/psql
      dockerfile: Dockerfile

  infra-ca:
    image: smallstep/step-ca
    ports:
      - 9000:9000
    environment:
      DOCKER_STEPCA_INIT_NAME: "ca.local"
      DOCKER_STEPCA_INIT_DNS_NAMES: "localhost,ca.local,step-ca"
    volumes:
      - ../infra/ca:/home/step